site_name: CoveAPI
site_description: Ready-to-use OpenAPI test coverage analysis tool that helps teams improve integration
site_url: https://coveapi.yezz.me/

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  favicon: img/logo.png
  features:
  - header.autohide
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  icon:
    repo: fontawesome/brands/github
  language: en
repo_name: CoveAPI
repo_url: https://github.com/yezz123/CoveAPI
edit_uri: ""

markdown_extensions:
  toc:
    permalink: true
  markdown.extensions.codehilite:
    guess_lang: false
  mdx_include:
    base_path: docs
  admonition:
  codehilite:
  extra:
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.tabbed:
    alternate_style: true
  attr_list:
  md_in_html:

plugins:
  search: null

nav:
  - About: index.md
  - configuration.md
  - postman.md
  - Frequently Asked Questions: faq.md
  - Development - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md

extra:
  analytics:
    provider: google
    property: G-7RF17YL4KP
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/yezz123
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/THyasser1
  - icon: fontawesome/solid/globe
    link: https://yezz.me

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
